import '../entities/models.dart';

abstract final class GameCatalog {
  static const List<ProductBlueprint> productBlueprints = <ProductBlueprint>[
    ProductBlueprint(
      id: 'company_website',
      name: 'Сайт компании',
      category: ProductCategory.saas,
      description:
          'Простой публичный сайт. Первый реалистичный релиз и вход в клиентские контракты.',
      baseDevelopmentCost: 18000,
      baseDevelopmentHours: 120,
      basePrice: 0,
      baseLatencyMs: 850,
      baseDesignScore: 48,
      baseSecurityScore: 42,
      baseReliability: 0.975,
      computePerThousandUsers: 1.5,
      expectedFeatureIds: <String>[
        'landing_page',
        'contact_form',
        'basic_analytics',
      ],
    ),
    ProductBlueprint(
      id: 'ai_assistant',
      name: 'AI-ассистент',
      category: ProductCategory.aiAssistant,
      description: 'Чат, генерация, поиск и автоматизация рабочих задач.',
      baseDevelopmentCost: 420000,
      baseDevelopmentHours: 920,
      basePrice: 1490,
      baseLatencyMs: 2600,
      baseDesignScore: 54,
      baseSecurityScore: 48,
      baseReliability: 0.955,
      computePerThousandUsers: 38,
      expectedFeatureIds: <String>[
        'chat_history',
        'file_analysis',
        'web_search',
        'team_spaces',
      ],
    ),
    ProductBlueprint(
      id: 'cloud_platform',
      name: 'Cloud-платформа',
      category: ProductCategory.cloud,
      description: 'Вычисления, базы данных, API и управляемое развёртывание.',
      baseDevelopmentCost: 680000,
      baseDevelopmentHours: 1400,
      basePrice: 6900,
      baseLatencyMs: 310,
      baseDesignScore: 46,
      baseSecurityScore: 58,
      baseReliability: 0.965,
      computePerThousandUsers: 24,
      expectedFeatureIds: <String>[
        'autoscaling',
        'managed_database',
        'monitoring',
        'multi_region',
      ],
    ),
    ProductBlueprint(
      id: 'team_saas',
      name: 'Командный SaaS',
      category: ProductCategory.saas,
      description: 'Задачи, документы, коммуникация и автоматизация команд.',
      baseDevelopmentCost: 360000,
      baseDevelopmentHours: 760,
      basePrice: 890,
      baseLatencyMs: 740,
      baseDesignScore: 60,
      baseSecurityScore: 52,
      baseReliability: 0.958,
      computePerThousandUsers: 12,
      expectedFeatureIds: <String>[
        'realtime_collaboration',
        'automation',
        'mobile_client',
        'analytics_dashboard',
      ],
    ),
    ProductBlueprint(
      id: 'privacy_browser',
      name: 'Браузер',
      category: ProductCategory.browser,
      description: 'Быстрый браузер с приватностью и встроенными сервисами.',
      baseDevelopmentCost: 740000,
      baseDevelopmentHours: 1800,
      basePrice: 390,
      baseLatencyMs: 590,
      baseDesignScore: 58,
      baseSecurityScore: 60,
      baseReliability: 0.972,
      computePerThousandUsers: 7,
      expectedFeatureIds: <String>[
        'tracker_blocking',
        'sync',
        'extension_store',
        'ai_sidebar',
      ],
    ),
    ProductBlueprint(
      id: 'crypto_wallet',
      name: 'Криптокошелёк',
      category: ProductCategory.cryptoWallet,
      description: 'Хранение, обмен, платежи и подключение к Web3-сервисам.',
      baseDevelopmentCost: 590000,
      baseDevelopmentHours: 1200,
      basePrice: 110,
      baseLatencyMs: 950,
      baseDesignScore: 55,
      baseSecurityScore: 62,
      baseReliability: 0.968,
      computePerThousandUsers: 18,
      expectedFeatureIds: <String>[
        'hardware_wallet',
        'fraud_monitoring',
        'multi_chain',
        'recovery',
      ],
    ),
    ProductBlueprint(
      id: 'city_system',
      name: 'Цифровая система города',
      category: ProductCategory.cloud,
      description:
          'Городская платформа: жители, службы, платежи, транспорт и интеграции. Требует пять инвесторов.',
      baseDevelopmentCost: 600000,
      baseDevelopmentHours: 12000,
      basePrice: 180000,
      baseLatencyMs: 480,
      baseDesignScore: 58,
      baseSecurityScore: 72,
      baseReliability: 0.982,
      computePerThousandUsers: 42,
      expectedFeatureIds: <String>[
        'public_portal',
        'identity_access',
        'city_integrations',
        'monitoring',
        'multi_region',
      ],
    ),
    ProductBlueprint(
      id: 'developer_platform',
      name: 'Developer platform',
      category: ProductCategory.developerTool,
      description: 'SDK, API, CI/CD и инструменты для разработчиков.',
      baseDevelopmentCost: 510000,
      baseDevelopmentHours: 1050,
      basePrice: 3200,
      baseLatencyMs: 420,
      baseDesignScore: 48,
      baseSecurityScore: 59,
      baseReliability: 0.971,
      computePerThousandUsers: 20,
      expectedFeatureIds: <String>[
        'sdk',
        'ci_cd',
        'observability',
        'api_gateway',
      ],
    ),
  ];

  static const List<FrameworkOption> frameworks = <FrameworkOption>[
    FrameworkOption(
      id: 'static_web',
      name: 'Static HTML/CSS/JS',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description:
          'Минимальная сложность и стоимость. Только простой сайт без тяжёлого backend.',
      performanceDelta: 12,
      designDelta: 0,
      securityDelta: 3,
      developmentSpeedDelta: 38,
      monthlyCost: 2500,
    ),
    FrameworkOption(
      id: 'laravel_web',
      name: 'Laravel + Blade',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description:
          'Быстрый корпоративный web и админка, но не лучший выбор для realtime.',
      performanceDelta: 0,
      designDelta: 3,
      securityDelta: 2,
      developmentSpeedDelta: 24,
      monthlyCost: 8500,
    ),
    FrameworkOption(
      id: 'java_enterprise',
      name: 'Java enterprise platform',
      supportedCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.saas,
        ProductCategory.developerTool,
      ],
      description:
          'Зрелая архитектура для больших систем и команд ценой медленного старта.',
      performanceDelta: 11,
      designDelta: 0,
      securityDelta: 8,
      developmentSpeedDelta: -10,
      monthlyCost: 42000,
    ),
    FrameworkOption(
      id: 'flutter_firebase',
      name: 'Flutter + Firebase',
      supportedCategories: <ProductCategory>[
        ProductCategory.saas,
        ProductCategory.cryptoWallet,
        ProductCategory.aiAssistant,
      ],
      description:
          'Быстрый mobile-first запуск, но ограниченный контроль backend.',
      performanceDelta: -3,
      designDelta: 8,
      securityDelta: -2,
      developmentSpeedDelta: 22,
      monthlyCost: 28000,
    ),
    FrameworkOption(
      id: 'next_nest',
      name: 'Next.js + NestJS',
      supportedCategories: <ProductCategory>[
        ProductCategory.saas,
        ProductCategory.aiAssistant,
        ProductCategory.developerTool,
      ],
      description: 'Быстрый web-релиз и большой рынок специалистов.',
      performanceDelta: 5,
      designDelta: 7,
      securityDelta: 1,
      developmentSpeedDelta: 15,
      monthlyCost: 18000,
    ),
    FrameworkOption(
      id: 'fastapi_react',
      name: 'FastAPI + React',
      supportedCategories: <ProductCategory>[
        ProductCategory.aiAssistant,
        ProductCategory.saas,
        ProductCategory.developerTool,
      ],
      description:
          'Удобно для AI и быстрых API, требует дисциплины инфраструктуры.',
      performanceDelta: 9,
      designDelta: 5,
      securityDelta: 0,
      developmentSpeedDelta: 18,
      monthlyCost: 22000,
    ),
    FrameworkOption(
      id: 'go_microservices',
      name: 'Go microservices',
      supportedCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.developerTool,
        ProductCategory.cryptoWallet,
      ],
      description:
          'Высокая производительность и умеренная сложность эксплуатации.',
      performanceDelta: 18,
      designDelta: 0,
      securityDelta: 6,
      developmentSpeedDelta: -4,
      monthlyCost: 26000,
    ),
    FrameworkOption(
      id: 'rust_core',
      name: 'Rust core + native UI',
      supportedCategories: <ProductCategory>[
        ProductCategory.browser,
        ProductCategory.cryptoWallet,
        ProductCategory.cloud,
      ],
      description:
          'Максимальный контроль скорости и памяти, дорогая разработка.',
      performanceDelta: 28,
      designDelta: 2,
      securityDelta: 12,
      developmentSpeedDelta: -18,
      monthlyCost: 34000,
    ),
    FrameworkOption(
      id: 'chromium_fork',
      name: 'Chromium fork',
      supportedCategories: <ProductCategory>[ProductCategory.browser],
      description: 'Быстрый выход на рынок, но большой технический долг.',
      performanceDelta: 8,
      designDelta: 4,
      securityDelta: 2,
      developmentSpeedDelta: 26,
      monthlyCost: 46000,
    ),
  ];

  static const List<LanguageOption> languages = <LanguageOption>[
    LanguageOption(
      id: 'html_css',
      name: 'HTML + CSS',
      performanceDelta: 8,
      reliabilityDelta: 0.003,
      talentAvailability: 98,
      monthlyCost: 0,
    ),
    LanguageOption(
      id: 'javascript',
      name: 'JavaScript',
      performanceDelta: 0,
      reliabilityDelta: -0.002,
      talentAvailability: 96,
      monthlyCost: 0,
    ),
    LanguageOption(
      id: 'php',
      name: 'PHP',
      performanceDelta: -1,
      reliabilityDelta: 0,
      talentAvailability: 88,
      monthlyCost: 0,
    ),
    LanguageOption(
      id: 'cpp',
      name: 'C++',
      performanceDelta: 24,
      reliabilityDelta: -0.003,
      talentAvailability: 44,
      monthlyCost: 11000,
    ),
    LanguageOption(
      id: 'java',
      name: 'Java',
      performanceDelta: 10,
      reliabilityDelta: 0.007,
      talentAvailability: 76,
      monthlyCost: 5500,
    ),
    LanguageOption(
      id: 'typescript',
      name: 'TypeScript',
      performanceDelta: 2,
      reliabilityDelta: 0.002,
      talentAvailability: 92,
      monthlyCost: 0,
    ),
    LanguageOption(
      id: 'python',
      name: 'Python',
      performanceDelta: -6,
      reliabilityDelta: -0.002,
      talentAvailability: 90,
      monthlyCost: 0,
    ),
    LanguageOption(
      id: 'go',
      name: 'Go',
      performanceDelta: 12,
      reliabilityDelta: 0.006,
      talentAvailability: 72,
      monthlyCost: 4000,
    ),
    LanguageOption(
      id: 'rust',
      name: 'Rust',
      performanceDelta: 20,
      reliabilityDelta: 0.009,
      talentAvailability: 48,
      monthlyCost: 9000,
    ),
    LanguageOption(
      id: 'dart',
      name: 'Dart',
      performanceDelta: 5,
      reliabilityDelta: 0.003,
      talentAvailability: 61,
      monthlyCost: 2000,
    ),
    LanguageOption(
      id: 'swift',
      name: 'Swift',
      performanceDelta: 11,
      reliabilityDelta: 0.006,
      talentAvailability: 58,
      monthlyCost: 6000,
    ),
    LanguageOption(
      id: 'kotlin',
      name: 'Kotlin',
      performanceDelta: 9,
      reliabilityDelta: 0.005,
      talentAvailability: 64,
      monthlyCost: 5000,
    ),
  ];

  static const List<TechnologyOption> technologies = <TechnologyOption>[
    TechnologyOption(
      id: 'postgresql',
      name: 'PostgreSQL',
      description: 'Надёжное основное хранилище.',
      performanceDelta: 3,
      securityDelta: 3,
      reliabilityDelta: 0.004,
      computeMultiplier: 1.04,
      developmentCost: 26000,
      monthlyCost: 9000,
    ),
    TechnologyOption(
      id: 'redis',
      name: 'Redis cache',
      description: 'Снижает задержку, но требует контроля консистентности.',
      performanceDelta: 17,
      securityDelta: -1,
      reliabilityDelta: -0.001,
      computeMultiplier: 1.08,
      developmentCost: 34000,
      monthlyCost: 12000,
    ),
    TechnologyOption(
      id: 'kubernetes',
      name: 'Kubernetes',
      description: 'Масштабирование и автоматизация ценой сложности.',
      performanceDelta: 4,
      securityDelta: 2,
      reliabilityDelta: 0.009,
      computeMultiplier: 1.12,
      developmentCost: 76000,
      monthlyCost: 24000,
    ),
    TechnologyOption(
      id: 'cdn',
      name: 'Global CDN',
      description: 'Снижает latency для распределённой аудитории.',
      performanceDelta: 23,
      securityDelta: 2,
      reliabilityDelta: 0.004,
      computeMultiplier: 1.05,
      developmentCost: 44000,
      monthlyCost: 17000,
    ),
    TechnologyOption(
      id: 'e2ee',
      name: 'End-to-end encryption',
      description: 'Повышает доверие и безопасность, усложняет разработку.',
      performanceDelta: -5,
      securityDelta: 20,
      reliabilityDelta: 0.001,
      computeMultiplier: 1.09,
      developmentCost: 88000,
      monthlyCost: 10000,
    ),
    TechnologyOption(
      id: 'hsm',
      name: 'HSM key storage',
      description: 'Защита ключей и транзакций на аппаратном уровне.',
      performanceDelta: -3,
      securityDelta: 28,
      reliabilityDelta: 0.006,
      computeMultiplier: 1.06,
      developmentCost: 130000,
      monthlyCost: 36000,
    ),
    TechnologyOption(
      id: 'vector_db',
      name: 'Vector database',
      description: 'Улучшает поиск и память AI-продуктов.',
      performanceDelta: 7,
      securityDelta: 0,
      reliabilityDelta: 0.002,
      computeMultiplier: 1.22,
      developmentCost: 64000,
      monthlyCost: 28000,
    ),
    TechnologyOption(
      id: 'observability_stack',
      name: 'Observability stack',
      description: 'Метрики, трассировка, алерты и ускорение реакции на сбои.',
      performanceDelta: 1,
      securityDelta: 5,
      reliabilityDelta: 0.012,
      computeMultiplier: 1.05,
      developmentCost: 52000,
      monthlyCost: 19000,
    ),
  ];

  static const List<FeatureOption> features = <FeatureOption>[
    FeatureOption(
      id: 'landing_page',
      name: 'Главная и страницы компании',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description: 'Контент, навигация и адаптивная вёрстка.',
      designDelta: 8,
      performanceDelta: 3,
      securityDelta: 0,
      retentionDelta: 0.005,
      computeMultiplier: 1.01,
      developmentCost: 18000,
    ),
    FeatureOption(
      id: 'contact_form',
      name: 'Формы и заявки',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description: 'Формы обратной связи и сохранение заявок.',
      designDelta: 3,
      performanceDelta: -1,
      securityDelta: -1,
      retentionDelta: 0.01,
      computeMultiplier: 1.02,
      developmentCost: 22000,
    ),
    FeatureOption(
      id: 'basic_analytics',
      name: 'Базовая аналитика сайта',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description: 'Просмотры, источники трафика и конверсии.',
      designDelta: 1,
      performanceDelta: -1,
      securityDelta: 0,
      retentionDelta: 0.008,
      computeMultiplier: 1.03,
      developmentCost: 16000,
    ),
    FeatureOption(
      id: 'public_portal',
      name: 'Портал жителя',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description: 'Обращения, услуги и статусы городских процессов.',
      designDelta: 10,
      performanceDelta: -6,
      securityDelta: 2,
      retentionDelta: 0.06,
      computeMultiplier: 1.25,
      developmentCost: 260000,
    ),
    FeatureOption(
      id: 'identity_access',
      name: 'Единая идентификация',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description:
          'Роли, организации и безопасный доступ к городским сервисам.',
      designDelta: 3,
      performanceDelta: -5,
      securityDelta: 18,
      retentionDelta: 0.04,
      computeMultiplier: 1.18,
      developmentCost: 310000,
    ),
    FeatureOption(
      id: 'city_integrations',
      name: 'Интеграции городских служб',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description: 'Транспорт, ЖКХ, платежи, медицина и внешние реестры.',
      designDelta: 6,
      performanceDelta: -8,
      securityDelta: -2,
      retentionDelta: 0.08,
      computeMultiplier: 1.40,
      developmentCost: 420000,
    ),
    FeatureOption(
      id: 'chat_history',
      name: 'История и память',
      supportedCategories: <ProductCategory>[ProductCategory.aiAssistant],
      description: 'Контекст между сессиями.',
      designDelta: 3,
      performanceDelta: -3,
      securityDelta: -2,
      retentionDelta: 0.035,
      computeMultiplier: 1.12,
      developmentCost: 42000,
    ),
    FeatureOption(
      id: 'file_analysis',
      name: 'Анализ файлов',
      supportedCategories: <ProductCategory>[ProductCategory.aiAssistant],
      description: 'Документы, таблицы и презентации.',
      designDelta: 5,
      performanceDelta: -6,
      securityDelta: -3,
      retentionDelta: 0.045,
      computeMultiplier: 1.18,
      developmentCost: 78000,
    ),
    FeatureOption(
      id: 'web_search',
      name: 'Поиск в интернете',
      supportedCategories: <ProductCategory>[ProductCategory.aiAssistant],
      description: 'Свежие ответы с источниками.',
      designDelta: 2,
      performanceDelta: -8,
      securityDelta: -2,
      retentionDelta: 0.04,
      computeMultiplier: 1.20,
      developmentCost: 93000,
    ),
    FeatureOption(
      id: 'team_spaces',
      name: 'Командные пространства',
      supportedCategories: <ProductCategory>[
        ProductCategory.aiAssistant,
        ProductCategory.saas,
      ],
      description: 'Общие проекты и права доступа.',
      designDelta: 6,
      performanceDelta: -2,
      securityDelta: 2,
      retentionDelta: 0.05,
      computeMultiplier: 1.10,
      developmentCost: 68000,
    ),
    FeatureOption(
      id: 'autoscaling',
      name: 'Автомасштабирование',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description: 'Автоматически добавляет ресурсы под нагрузкой.',
      designDelta: 1,
      performanceDelta: 10,
      securityDelta: 1,
      retentionDelta: 0.025,
      computeMultiplier: 1.08,
      developmentCost: 110000,
    ),
    FeatureOption(
      id: 'managed_database',
      name: 'Managed database',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description: 'Базы данных без ручного администрирования.',
      designDelta: 5,
      performanceDelta: 5,
      securityDelta: 5,
      retentionDelta: 0.04,
      computeMultiplier: 1.16,
      developmentCost: 126000,
    ),
    FeatureOption(
      id: 'monitoring',
      name: 'Мониторинг и алерты',
      supportedCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.developerTool,
      ],
      description: 'Понятное состояние систем в реальном времени.',
      designDelta: 4,
      performanceDelta: 2,
      securityDelta: 4,
      retentionDelta: 0.035,
      computeMultiplier: 1.07,
      developmentCost: 72000,
    ),
    FeatureOption(
      id: 'multi_region',
      name: 'Multi-region',
      supportedCategories: <ProductCategory>[ProductCategory.cloud],
      description: 'Резервирование и близость к клиентам.',
      designDelta: 1,
      performanceDelta: 18,
      securityDelta: 3,
      retentionDelta: 0.045,
      computeMultiplier: 1.28,
      developmentCost: 190000,
    ),
    FeatureOption(
      id: 'realtime_collaboration',
      name: 'Совместная работа',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description: 'Одновременное редактирование и комментарии.',
      designDelta: 9,
      performanceDelta: -5,
      securityDelta: 0,
      retentionDelta: 0.055,
      computeMultiplier: 1.20,
      developmentCost: 96000,
    ),
    FeatureOption(
      id: 'automation',
      name: 'Автоматизации',
      supportedCategories: <ProductCategory>[
        ProductCategory.saas,
        ProductCategory.developerTool,
      ],
      description: 'Триггеры, правила и сценарии.',
      designDelta: 5,
      performanceDelta: -3,
      securityDelta: -1,
      retentionDelta: 0.05,
      computeMultiplier: 1.16,
      developmentCost: 82000,
    ),
    FeatureOption(
      id: 'mobile_client',
      name: 'Мобильный клиент',
      supportedCategories: <ProductCategory>[ProductCategory.saas],
      description: 'Работа с телефона без урезанного функционала.',
      designDelta: 10,
      performanceDelta: 2,
      securityDelta: 1,
      retentionDelta: 0.045,
      computeMultiplier: 1.08,
      developmentCost: 105000,
    ),
    FeatureOption(
      id: 'analytics_dashboard',
      name: 'Аналитика',
      supportedCategories: <ProductCategory>[
        ProductCategory.saas,
        ProductCategory.developerTool,
      ],
      description: 'Показатели использования и эффективности.',
      designDelta: 7,
      performanceDelta: -2,
      securityDelta: 0,
      retentionDelta: 0.035,
      computeMultiplier: 1.12,
      developmentCost: 67000,
    ),
    FeatureOption(
      id: 'tracker_blocking',
      name: 'Блокировка трекеров',
      supportedCategories: <ProductCategory>[ProductCategory.browser],
      description: 'Приватность и чистая загрузка страниц.',
      designDelta: 3,
      performanceDelta: 15,
      securityDelta: 9,
      retentionDelta: 0.035,
      computeMultiplier: 1.02,
      developmentCost: 88000,
    ),
    FeatureOption(
      id: 'sync',
      name: 'Синхронизация',
      supportedCategories: <ProductCategory>[ProductCategory.browser],
      description: 'Вкладки, пароли и история на всех устройствах.',
      designDelta: 8,
      performanceDelta: -2,
      securityDelta: -2,
      retentionDelta: 0.055,
      computeMultiplier: 1.10,
      developmentCost: 112000,
    ),
    FeatureOption(
      id: 'extension_store',
      name: 'Магазин расширений',
      supportedCategories: <ProductCategory>[ProductCategory.browser],
      description: 'Экосистема расширений и разработчиков.',
      designDelta: 7,
      performanceDelta: -6,
      securityDelta: -5,
      retentionDelta: 0.06,
      computeMultiplier: 1.12,
      developmentCost: 160000,
    ),
    FeatureOption(
      id: 'ai_sidebar',
      name: 'AI-панель',
      supportedCategories: <ProductCategory>[ProductCategory.browser],
      description: 'Ассистент и работа со страницей.',
      designDelta: 9,
      performanceDelta: -7,
      securityDelta: -2,
      retentionDelta: 0.05,
      computeMultiplier: 1.22,
      developmentCost: 135000,
    ),
    FeatureOption(
      id: 'hardware_wallet',
      name: 'Аппаратные кошельки',
      supportedCategories: <ProductCategory>[ProductCategory.cryptoWallet],
      description: 'Подключение физических устройств хранения ключей.',
      designDelta: 3,
      performanceDelta: -2,
      securityDelta: 18,
      retentionDelta: 0.045,
      computeMultiplier: 1.03,
      developmentCost: 118000,
    ),
    FeatureOption(
      id: 'fraud_monitoring',
      name: 'Антифрод',
      supportedCategories: <ProductCategory>[ProductCategory.cryptoWallet],
      description: 'Риск-скоринг транзакций и предупреждения.',
      designDelta: 4,
      performanceDelta: -5,
      securityDelta: 24,
      retentionDelta: 0.055,
      computeMultiplier: 1.15,
      developmentCost: 145000,
    ),
    FeatureOption(
      id: 'multi_chain',
      name: 'Multi-chain',
      supportedCategories: <ProductCategory>[ProductCategory.cryptoWallet],
      description: 'Несколько сетей в одном приложении.',
      designDelta: 8,
      performanceDelta: -8,
      securityDelta: -4,
      retentionDelta: 0.06,
      computeMultiplier: 1.24,
      developmentCost: 175000,
    ),
    FeatureOption(
      id: 'recovery',
      name: 'Социальное восстановление',
      supportedCategories: <ProductCategory>[ProductCategory.cryptoWallet],
      description: 'Возврат доступа без хранения seed-фразы компанией.',
      designDelta: 8,
      performanceDelta: -2,
      securityDelta: 12,
      retentionDelta: 0.05,
      computeMultiplier: 1.08,
      developmentCost: 132000,
    ),
    FeatureOption(
      id: 'sdk',
      name: 'SDK',
      supportedCategories: <ProductCategory>[ProductCategory.developerTool],
      description: 'Библиотеки и примеры для быстрого старта.',
      designDelta: 6,
      performanceDelta: 3,
      securityDelta: 2,
      retentionDelta: 0.045,
      computeMultiplier: 1.05,
      developmentCost: 76000,
    ),
    FeatureOption(
      id: 'ci_cd',
      name: 'CI/CD',
      supportedCategories: <ProductCategory>[ProductCategory.developerTool],
      description: 'Сборка, тесты и доставка из единого интерфейса.',
      designDelta: 7,
      performanceDelta: 6,
      securityDelta: 3,
      retentionDelta: 0.055,
      computeMultiplier: 1.18,
      developmentCost: 122000,
    ),
    FeatureOption(
      id: 'observability',
      name: 'Observability',
      supportedCategories: <ProductCategory>[ProductCategory.developerTool],
      description: 'Логи, метрики, трассировка и профилирование.',
      designDelta: 6,
      performanceDelta: 4,
      securityDelta: 4,
      retentionDelta: 0.05,
      computeMultiplier: 1.14,
      developmentCost: 106000,
    ),
    FeatureOption(
      id: 'api_gateway',
      name: 'API gateway',
      supportedCategories: <ProductCategory>[ProductCategory.developerTool],
      description: 'Ключи, лимиты, маршрутизация и биллинг API.',
      designDelta: 5,
      performanceDelta: 7,
      securityDelta: 9,
      retentionDelta: 0.045,
      computeMultiplier: 1.12,
      developmentCost: 98000,
    ),
  ];

  static const List<Candidate> initialCandidates = <Candidate>[
    Candidate(
      id: 'c_anna',
      name: 'Анна Миронова',
      role: EmployeeRole.frontend,
      skill: 78,
      speed: 84,
      quality: 73,
      autonomy: 68,
      communication: 80,
      reliability: 74,
      salary: 165000,
      loyalty: 72,
      remote: true,
      languageIds: <String>['html_css', 'javascript', 'typescript'],
    ),
    Candidate(
      id: 'c_timur',
      name: 'Тимур Сафин',
      role: EmployeeRole.backend,
      skill: 88,
      speed: 71,
      quality: 86,
      autonomy: 82,
      communication: 61,
      reliability: 89,
      salary: 245000,
      loyalty: 67,
      remote: false,
      languageIds: <String>['go', 'java', 'typescript'],
    ),
    Candidate(
      id: 'c_daria',
      name: 'Дарья Ли',
      role: EmployeeRole.designer,
      skill: 83,
      speed: 77,
      quality: 91,
      autonomy: 73,
      communication: 87,
      reliability: 76,
      salary: 190000,
      loyalty: 79,
      remote: true,
      languageIds: <String>['html_css', 'javascript'],
    ),
    Candidate(
      id: 'c_ilya',
      name: 'Илья Воронцов',
      role: EmployeeRole.devOps,
      skill: 86,
      speed: 67,
      quality: 84,
      autonomy: 88,
      communication: 62,
      reliability: 94,
      salary: 260000,
      loyalty: 75,
      remote: false,
      languageIds: <String>['go', 'python', 'java'],
    ),
    Candidate(
      id: 'c_sonya',
      name: 'Софья Орлова',
      role: EmployeeRole.growth,
      skill: 80,
      speed: 82,
      quality: 69,
      autonomy: 76,
      communication: 90,
      reliability: 66,
      salary: 185000,
      loyalty: 65,
      remote: true,
      languageIds: <String>['javascript'],
    ),
    Candidate(
      id: 'c_maksim',
      name: 'Максим Руденко',
      role: EmployeeRole.productManager,
      skill: 85,
      speed: 75,
      quality: 82,
      autonomy: 84,
      communication: 91,
      reliability: 81,
      salary: 270000,
      loyalty: 71,
      remote: false,
      languageIds: <String>['typescript', 'python'],
    ),
    Candidate(
      id: 'c_alina',
      name: 'Алина Коваль',
      role: EmployeeRole.mobile,
      skill: 72,
      speed: 88,
      quality: 70,
      autonomy: 63,
      communication: 78,
      reliability: 68,
      salary: 145000,
      loyalty: 82,
      remote: true,
      languageIds: <String>['dart', 'kotlin', 'swift'],
    ),
    Candidate(
      id: 'c_roman',
      name: 'Роман Хан',
      role: EmployeeRole.sales,
      skill: 84,
      speed: 73,
      quality: 76,
      autonomy: 80,
      communication: 94,
      reliability: 73,
      salary: 235000,
      loyalty: 62,
      remote: false,
      languageIds: <String>[],
    ),
    Candidate(
      id: 'c_nikita',
      name: 'Никита Волков',
      role: EmployeeRole.security,
      skill: 89,
      speed: 66,
      quality: 92,
      autonomy: 86,
      communication: 59,
      reliability: 96,
      salary: 295000,
      loyalty: 77,
      remote: true,
      languageIds: <String>['rust', 'go', 'cpp'],
    ),
    Candidate(
      id: 'c_vika',
      name: 'Виктория Громова',
      role: EmployeeRole.qa,
      skill: 77,
      speed: 79,
      quality: 88,
      autonomy: 74,
      communication: 84,
      reliability: 91,
      salary: 175000,
      loyalty: 83,
      remote: true,
      languageIds: <String>['typescript', 'python', 'java'],
    ),
    Candidate(
      id: 'c_egor',
      name: 'Егор Павлов',
      role: EmployeeRole.aiMl,
      skill: 82,
      speed: 76,
      quality: 78,
      autonomy: 72,
      communication: 64,
      reliability: 70,
      salary: 255000,
      loyalty: 58,
      remote: false,
      languageIds: <String>['python', 'go'],
    ),
    Candidate(
      id: 'c_maria',
      name: 'Мария Белова',
      role: EmployeeRole.support,
      skill: 69,
      speed: 86,
      quality: 75,
      autonomy: 70,
      communication: 92,
      reliability: 79,
      salary: 120000,
      loyalty: 88,
      remote: true,
      languageIds: <String>[],
    ),
    Candidate(
      id: 'c_oleg',
      name: 'Олег Фомин',
      role: EmployeeRole.backend,
      skill: 74,
      speed: 82,
      quality: 72,
      autonomy: 76,
      communication: 67,
      reliability: 78,
      salary: 135000,
      loyalty: 76,
      remote: true,
      languageIds: <String>['php', 'javascript'],
    ),
    Candidate(
      id: 'c_lena',
      name: 'Елена Тихонова',
      role: EmployeeRole.frontend,
      skill: 71,
      speed: 87,
      quality: 74,
      autonomy: 69,
      communication: 81,
      reliability: 73,
      salary: 125000,
      loyalty: 80,
      remote: true,
      languageIds: <String>['html_css', 'javascript', 'typescript'],
    ),
    Candidate(
      id: 'c_artem',
      name: 'Артём Чернов',
      role: EmployeeRole.frontend,
      skill: 84,
      speed: 79,
      quality: 85,
      autonomy: 77,
      communication: 74,
      reliability: 81,
      salary: 205000,
      loyalty: 69,
      remote: false,
      languageIds: <String>['typescript', 'javascript'],
    ),
    Candidate(
      id: 'c_pavel',
      name: 'Павел Ким',
      role: EmployeeRole.backend,
      skill: 91,
      speed: 68,
      quality: 90,
      autonomy: 88,
      communication: 58,
      reliability: 92,
      salary: 305000,
      loyalty: 64,
      remote: true,
      languageIds: <String>['cpp', 'rust', 'go'],
    ),
    Candidate(
      id: 'c_irina',
      name: 'Ирина Лазарева',
      role: EmployeeRole.security,
      skill: 87,
      speed: 70,
      quality: 93,
      autonomy: 84,
      communication: 66,
      reliability: 95,
      salary: 285000,
      loyalty: 74,
      remote: true,
      languageIds: <String>['rust', 'go', 'java'],
    ),
    Candidate(
      id: 'c_sergey',
      name: 'Сергей Данилов',
      role: EmployeeRole.backend,
      skill: 82,
      speed: 75,
      quality: 84,
      autonomy: 78,
      communication: 71,
      reliability: 86,
      salary: 225000,
      loyalty: 72,
      remote: false,
      languageIds: <String>['java', 'kotlin'],
    ),
    Candidate(
      id: 'c_ksenia',
      name: 'Ксения Романова',
      role: EmployeeRole.productManager,
      skill: 79,
      speed: 78,
      quality: 83,
      autonomy: 81,
      communication: 90,
      reliability: 80,
      salary: 220000,
      loyalty: 77,
      remote: true,
      languageIds: <String>['java', 'typescript'],
    ),
    Candidate(
      id: 'c_andrey',
      name: 'Андрей Зотов',
      role: EmployeeRole.devOps,
      skill: 84,
      speed: 74,
      quality: 82,
      autonomy: 86,
      communication: 65,
      reliability: 93,
      salary: 255000,
      loyalty: 73,
      remote: true,
      languageIds: <String>['go', 'java', 'python'],
    ),
    Candidate(
      id: 'c_tatiana',
      name: 'Татьяна Юдина',
      role: EmployeeRole.mobile,
      skill: 81,
      speed: 80,
      quality: 86,
      autonomy: 75,
      communication: 79,
      reliability: 83,
      salary: 215000,
      loyalty: 78,
      remote: true,
      languageIds: <String>['swift', 'kotlin', 'dart'],
    ),
    Candidate(
      id: 'c_lev',
      name: 'Лев Назаров',
      role: EmployeeRole.aiMl,
      skill: 88,
      speed: 72,
      quality: 87,
      autonomy: 83,
      communication: 63,
      reliability: 82,
      salary: 290000,
      loyalty: 66,
      remote: false,
      languageIds: <String>['python', 'typescript', 'go'],
    ),
    Candidate(
      id: 'c_olga',
      name: 'Ольга Демина',
      role: EmployeeRole.qa,
      skill: 80,
      speed: 77,
      quality: 92,
      autonomy: 73,
      communication: 85,
      reliability: 94,
      salary: 195000,
      loyalty: 84,
      remote: true,
      languageIds: <String>['cpp', 'rust', 'java'],
    ),
    Candidate(
      id: 'c_denise',
      name: 'Денис Соколов',
      role: EmployeeRole.sales,
      skill: 76,
      speed: 84,
      quality: 73,
      autonomy: 79,
      communication: 95,
      reliability: 75,
      salary: 180000,
      loyalty: 71,
      remote: true,
      languageIds: <String>[],
    ),
    Candidate(
      id: 'c_hr_natalia',
      name: 'Наталья Морозова',
      role: EmployeeRole.productManager,
      skill: 76,
      speed: 79,
      quality: 80,
      autonomy: 82,
      communication: 94,
      reliability: 86,
      salary: 155000,
      loyalty: 84,
      remote: true,
      languageIds: <String>[],
      isHr: true,
    ),
  ];

  static const List<OfficeOption> offices = <OfficeOption>[
    OfficeOption(
      id: 'garage',
      name: 'Домашний гараж',
      group: 'Старт',
      description: 'Минимальный burn rate. Подходит для небольшой команды.',
      monthlyRent: 35000,
      deposit: 70000,
      capacity: 3,
      comfortScore: 42,
      communicationEfficiency: 0.91,
      hiringBoostPercent: 0,
      prestigeScore: 18,
    ),
    OfficeOption(
      id: 'coworking',
      name: 'Коворкинг District',
      group: 'Старт',
      description: 'Гибкая аренда, переговорные и инфраструктура.',
      monthlyRent: 145000,
      deposit: 145000,
      capacity: 8,
      comfortScore: 68,
      communicationEfficiency: 0.96,
      hiringBoostPercent: 0.04,
      prestigeScore: 38,
    ),
    OfficeOption(
      id: 'studio',
      name: 'Собственная студия',
      group: 'Рост',
      description: 'Стабильная культура и отдельные зоны для команд.',
      monthlyRent: 360000,
      deposit: 720000,
      capacity: 18,
      comfortScore: 79,
      communicationEfficiency: 1.02,
      hiringBoostPercent: 0.08,
      prestigeScore: 58,
    ),
    OfficeOption(
      id: 'tech_loft',
      name: 'Tech Loft',
      group: 'Рост',
      description: 'Высокий престиж для найма и встреч с инвесторами.',
      monthlyRent: 790000,
      deposit: 1580000,
      capacity: 36,
      comfortScore: 88,
      communicationEfficiency: 1.07,
      hiringBoostPercent: 0.13,
      prestigeScore: 78,
    ),
    OfficeOption(
      id: 'hq',
      name: 'FOUNDER HQ',
      group: 'Штаб-квартира',
      description: 'Подразделения, студия, лаборатория и мероприятия.',
      monthlyRent: 1850000,
      deposit: 3700000,
      capacity: 90,
      comfortScore: 94,
      communicationEfficiency: 1.11,
      hiringBoostPercent: 0.18,
      prestigeScore: 94,
    ),
  ];

  static const List<ServerRoomOption> serverRooms = <ServerRoomOption>[
    ServerRoomOption(
      id: 'closet',
      name: 'Технический шкаф',
      group: 'Старт',
      description: 'Минимальная серверная без резервного охлаждения.',
      monthlyRent: 18000,
      deposit: 36000,
      rackUnits: 8,
      coolingKw: 4.5,
      powerKw: 6.0,
      networkGbps: 1,
      physicalSecurityScore: 45,
    ),
    ServerRoomOption(
      id: 'micro_dc',
      name: 'Micro DC',
      group: 'Старт',
      description: 'Отдельное помещение, UPS и базовый климат-контроль.',
      monthlyRent: 110000,
      deposit: 220000,
      rackUnits: 24,
      coolingKw: 18,
      powerKw: 24,
      networkGbps: 10,
      physicalSecurityScore: 66,
    ),
    ServerRoomOption(
      id: 'private_cage',
      name: 'Private data-center cage',
      group: 'Рост',
      description: 'Выделенная зона в дата-центре с резервированием.',
      monthlyRent: 390000,
      deposit: 780000,
      rackUnits: 72,
      coolingKw: 68,
      powerKw: 90,
      networkGbps: 40,
      physicalSecurityScore: 86,
    ),
    ServerRoomOption(
      id: 'regional_dc',
      name: 'Regional data center',
      group: 'Масштаб',
      description: 'Собственный контур для большой экосистемы.',
      monthlyRent: 1450000,
      deposit: 2900000,
      rackUnits: 240,
      coolingKw: 260,
      powerKw: 340,
      networkGbps: 200,
      physicalSecurityScore: 96,
    ),
  ];

  static const List<ServerHardwareOption> serverHardware =
      <ServerHardwareOption>[
        ServerHardwareOption(
          id: 'edge_s1',
          name: 'Edge S1',
          group: 'Compute',
          description: 'Компактный сервер для раннего продукта.',
          purchaseCost: 180000,
          monthlyCost: 9000,
          rackUnits: 2,
          computeUnits: 130,
          powerKw: 0.9,
          heatKw: 0.8,
          networkGbps: 1,
          hardwareReliability: 0.975,
        ),
        ServerHardwareOption(
          id: 'compute_m4',
          name: 'Compute M4',
          group: 'Compute',
          description: 'Универсальный сервер приложений и баз данных.',
          purchaseCost: 520000,
          monthlyCost: 19000,
          rackUnits: 4,
          computeUnits: 480,
          powerKw: 2.6,
          heatKw: 2.3,
          networkGbps: 5,
          hardwareReliability: 0.988,
        ),
        ServerHardwareOption(
          id: 'ai_gpu_g2',
          name: 'AI GPU G2',
          group: 'AI',
          description: 'GPU-узел для inference и обучения моделей.',
          purchaseCost: 1180000,
          monthlyCost: 52000,
          rackUnits: 6,
          computeUnits: 1250,
          powerKw: 7.8,
          heatKw: 7.2,
          networkGbps: 10,
          hardwareReliability: 0.984,
        ),
        ServerHardwareOption(
          id: 'storage_r8',
          name: 'Storage R8',
          group: 'Storage',
          description: 'Надёжное хранилище и резервные копии.',
          purchaseCost: 740000,
          monthlyCost: 28000,
          rackUnits: 8,
          computeUnits: 210,
          powerKw: 3.2,
          heatKw: 2.8,
          networkGbps: 10,
          hardwareReliability: 0.994,
        ),
        ServerHardwareOption(
          id: 'cluster_x12',
          name: 'Cluster X12',
          group: 'Cluster',
          description: 'Высокоплотный кластер для массового трафика.',
          purchaseCost: 2650000,
          monthlyCost: 98000,
          rackUnits: 12,
          computeUnits: 3200,
          powerKw: 15.5,
          heatKw: 14.2,
          networkGbps: 40,
          hardwareReliability: 0.996,
        ),
      ];

  static const List<CompetitorBenchmark> competitors = <CompetitorBenchmark>[
    CompetitorBenchmark(
      id: 'comp_ai',
      companyName: 'Neural Peak',
      productName: 'Astra AI',
      category: ProductCategory.aiAssistant,
      speedMs: 1450,
      designScore: 82,
      securityScore: 76,
      reliability: 0.994,
      featureIds: <String>[
        'chat_history',
        'file_analysis',
        'web_search',
        'team_spaces',
      ],
      users: 4200000,
      monthlyPrice: 1690,
    ),
    CompetitorBenchmark(
      id: 'comp_cloud',
      companyName: 'Northstack',
      productName: 'North Cloud',
      category: ProductCategory.cloud,
      speedMs: 118,
      designScore: 74,
      securityScore: 88,
      reliability: 0.9992,
      featureIds: <String>[
        'autoscaling',
        'managed_database',
        'monitoring',
        'multi_region',
      ],
      users: 680000,
      monthlyPrice: 7600,
    ),
    CompetitorBenchmark(
      id: 'comp_saas',
      companyName: 'Boardly',
      productName: 'Boardly Work',
      category: ProductCategory.saas,
      speedMs: 330,
      designScore: 90,
      securityScore: 79,
      reliability: 0.998,
      featureIds: <String>[
        'realtime_collaboration',
        'automation',
        'mobile_client',
        'analytics_dashboard',
        'team_spaces',
      ],
      users: 2300000,
      monthlyPrice: 990,
    ),
    CompetitorBenchmark(
      id: 'comp_browser',
      companyName: 'Vela Systems',
      productName: 'Vela Browser',
      category: ProductCategory.browser,
      speedMs: 235,
      designScore: 86,
      securityScore: 84,
      reliability: 0.9985,
      featureIds: <String>[
        'tracker_blocking',
        'sync',
        'extension_store',
        'ai_sidebar',
      ],
      users: 12400000,
      monthlyPrice: 0,
    ),
    CompetitorBenchmark(
      id: 'comp_wallet',
      companyName: 'Vaultora',
      productName: 'Vaultora Wallet',
      category: ProductCategory.cryptoWallet,
      speedMs: 460,
      designScore: 81,
      securityScore: 94,
      reliability: 0.999,
      featureIds: <String>[
        'hardware_wallet',
        'fraud_monitoring',
        'multi_chain',
        'recovery',
      ],
      users: 1900000,
      monthlyPrice: 85,
    ),
    CompetitorBenchmark(
      id: 'comp_dev',
      companyName: 'Forgebit',
      productName: 'Forgebit Platform',
      category: ProductCategory.developerTool,
      speedMs: 175,
      designScore: 76,
      securityScore: 87,
      reliability: 0.999,
      featureIds: <String>[
        'sdk',
        'ci_cd',
        'observability',
        'api_gateway',
        'monitoring',
      ],
      users: 310000,
      monthlyPrice: 3500,
    ),
  ];

  static const List<MarketSegment> marketSegments = <MarketSegment>[
    MarketSegment(
      id: 'ai_speed',
      name: 'Power users',
      category: ProductCategory.aiAssistant,
      addressableUsers: 1800000,
      speedWeight: 0.40,
      designWeight: 0.10,
      securityWeight: 0.10,
      featureWeight: 0.30,
      priceWeight: 0.10,
    ),
    MarketSegment(
      id: 'ai_team',
      name: 'Команды',
      category: ProductCategory.aiAssistant,
      addressableUsers: 2400000,
      speedWeight: 0.15,
      designWeight: 0.20,
      securityWeight: 0.20,
      featureWeight: 0.35,
      priceWeight: 0.10,
    ),
    MarketSegment(
      id: 'cloud_reliability',
      name: 'B2B инфраструктура',
      category: ProductCategory.cloud,
      addressableUsers: 520000,
      speedWeight: 0.25,
      designWeight: 0.05,
      securityWeight: 0.30,
      featureWeight: 0.30,
      priceWeight: 0.10,
    ),
    MarketSegment(
      id: 'saas_design',
      name: 'Креативные команды',
      category: ProductCategory.saas,
      addressableUsers: 1700000,
      speedWeight: 0.10,
      designWeight: 0.40,
      securityWeight: 0.10,
      featureWeight: 0.30,
      priceWeight: 0.10,
    ),
    MarketSegment(
      id: 'saas_ops',
      name: 'Операционные команды',
      category: ProductCategory.saas,
      addressableUsers: 2100000,
      speedWeight: 0.15,
      designWeight: 0.15,
      securityWeight: 0.15,
      featureWeight: 0.40,
      priceWeight: 0.15,
    ),
    MarketSegment(
      id: 'browser_speed',
      name: 'Скорость и приватность',
      category: ProductCategory.browser,
      addressableUsers: 7600000,
      speedWeight: 0.38,
      designWeight: 0.16,
      securityWeight: 0.26,
      featureWeight: 0.15,
      priceWeight: 0.05,
    ),
    MarketSegment(
      id: 'wallet_security',
      name: 'Хранение капитала',
      category: ProductCategory.cryptoWallet,
      addressableUsers: 1600000,
      speedWeight: 0.05,
      designWeight: 0.10,
      securityWeight: 0.55,
      featureWeight: 0.25,
      priceWeight: 0.05,
    ),
    MarketSegment(
      id: 'wallet_active',
      name: 'Активные трейдеры',
      category: ProductCategory.cryptoWallet,
      addressableUsers: 1100000,
      speedWeight: 0.25,
      designWeight: 0.10,
      securityWeight: 0.30,
      featureWeight: 0.25,
      priceWeight: 0.10,
    ),
    MarketSegment(
      id: 'dev_speed',
      name: 'Developer teams',
      category: ProductCategory.developerTool,
      addressableUsers: 440000,
      speedWeight: 0.22,
      designWeight: 0.08,
      securityWeight: 0.20,
      featureWeight: 0.42,
      priceWeight: 0.08,
    ),
  ];

  static const List<InvestorProfile> investors = <InvestorProfile>[
    InvestorProfile(
      id: 'inv_aurora',
      name: 'Aurora Ventures',
      thesis: 'AI и developer tools на ранней стадии.',
      preferredCategories: <ProductCategory>[
        ProductCategory.aiAssistant,
        ProductCategory.developerTool,
      ],
      availableCapital: 500000,
      minimumReadiness: 0.35,
      riskTolerance: 0.72,
      maximumEquityPercent: 18,
    ),
    InvestorProfile(
      id: 'inv_north',
      name: 'Northline Capital',
      thesis: 'B2B SaaS, cloud и инфраструктура с выручкой.',
      preferredCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.saas,
      ],
      availableCapital: 1800000,
      minimumReadiness: 0.62,
      riskTolerance: 0.46,
      maximumEquityPercent: 15,
    ),
    InvestorProfile(
      id: 'inv_frontier',
      name: 'Frontier Labs',
      thesis: 'Рискованные технологии и криптоинфраструктура.',
      preferredCategories: <ProductCategory>[
        ProductCategory.cryptoWallet,
        ProductCategory.browser,
        ProductCategory.aiAssistant,
      ],
      availableCapital: 950000,
      minimumReadiness: 0.48,
      riskTolerance: 0.84,
      maximumEquityPercent: 22,
    ),
    InvestorProfile(
      id: 'inv_scale',
      name: 'Scale Partners',
      thesis: 'Продукты с подтверждённым рынком и сильной метрикой роста.',
      preferredCategories: <ProductCategory>[
        ProductCategory.aiAssistant,
        ProductCategory.cloud,
        ProductCategory.saas,
        ProductCategory.browser,
        ProductCategory.developerTool,
      ],
      availableCapital: 4200000,
      minimumReadiness: 0.78,
      riskTolerance: 0.35,
      maximumEquityPercent: 12,
    ),
    InvestorProfile(
      id: 'inv_civic',
      name: 'Civic Systems Fund',
      thesis: 'Городские сервисы, govtech и долгосрочная инфраструктура.',
      preferredCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.developerTool,
      ],
      availableCapital: 6500000,
      minimumReadiness: 0.66,
      riskTolerance: 0.42,
      maximumEquityPercent: 14,
    ),
    InvestorProfile(
      id: 'inv_atlas',
      name: 'Atlas Infrastructure',
      thesis: 'Крупные платформы, дата-центры и цифровая инфраструктура.',
      preferredCategories: <ProductCategory>[
        ProductCategory.cloud,
        ProductCategory.saas,
        ProductCategory.developerTool,
      ],
      availableCapital: 9000000,
      minimumReadiness: 0.72,
      riskTolerance: 0.38,
      maximumEquityPercent: 13,
    ),
  ];

  static const List<MarketCompany> marketCompanies = <MarketCompany>[
    MarketCompany(
      id: 'm_pixel',
      companyName: 'PixelForge',
      productName: 'CanvasFlow',
      category: ProductCategory.saas,
      description: 'Инструмент совместной работы для дизайн-команд.',
      valuation: 3200000,
      productPrice: 1850000,
      users: 64000,
      monthlyRevenue: 740000,
      monthlyProfit: 170000,
      growthRate: 0.09,
      securityScore: 71,
      speedMs: 410,
      designScore: 92,
      computeDemand: 210,
      availableStakePercent: 18,
    ),
    MarketCompany(
      id: 'm_guard',
      companyName: 'Keyguard Labs',
      productName: 'Keyguard Wallet',
      category: ProductCategory.cryptoWallet,
      description: 'Кошелёк с сильной безопасностью, но слабым дизайном.',
      valuation: 5100000,
      productPrice: 2900000,
      users: 118000,
      monthlyRevenue: 1120000,
      monthlyProfit: 260000,
      growthRate: 0.06,
      securityScore: 96,
      speedMs: 620,
      designScore: 61,
      computeDemand: 340,
      availableStakePercent: 12,
    ),
    MarketCompany(
      id: 'm_api',
      companyName: 'API Harbor',
      productName: 'Harbor API',
      category: ProductCategory.developerTool,
      description: 'API gateway и аналитика для небольших команд.',
      valuation: 2750000,
      productPrice: 1600000,
      users: 29000,
      monthlyRevenue: 610000,
      monthlyProfit: 145000,
      growthRate: 0.12,
      securityScore: 82,
      speedMs: 210,
      designScore: 73,
      computeDemand: 190,
      availableStakePercent: 20,
    ),
    MarketCompany(
      id: 'm_orbit',
      companyName: 'Orbit Edge',
      productName: 'Orbit Edge Cloud',
      category: ProductCategory.cloud,
      description: 'Региональная edge-инфраструктура с низкой задержкой.',
      valuation: 8800000,
      productPrice: 4900000,
      users: 86000,
      monthlyRevenue: 1980000,
      monthlyProfit: 390000,
      growthRate: 0.08,
      securityScore: 88,
      speedMs: 92,
      designScore: 68,
      computeDemand: 920,
      availableStakePercent: 10,
    ),
  ];

  static ProductBlueprint blueprintById(String id) =>
      productBlueprints.firstWhere((item) => item.id == id);
  static FrameworkOption frameworkById(String id) =>
      frameworks.firstWhere((item) => item.id == id);
  static LanguageOption languageById(String id) =>
      languages.firstWhere((item) => item.id == id);
  static TechnologyOption technologyById(String id) =>
      technologies.firstWhere((item) => item.id == id);
  static FeatureOption featureById(String id) =>
      features.firstWhere((item) => item.id == id);
  static OfficeOption officeById(String id) =>
      offices.firstWhere((item) => item.id == id);
  static ServerRoomOption serverRoomById(String id) =>
      serverRooms.firstWhere((item) => item.id == id);
  static ServerHardwareOption serverHardwareById(String id) =>
      serverHardware.firstWhere((item) => item.id == id);
  static CompetitorBenchmark competitorFor(ProductCategory category) =>
      competitors.firstWhere((item) => item.category == category);
  static InvestorProfile investorById(String id) =>
      investors.firstWhere((item) => item.id == id);
  static MarketCompany marketCompanyById(String id) =>
      marketCompanies.firstWhere((item) => item.id == id);
}
