abstract final class V12LocalizationLexicon {
  static const Map<String, String> exact = <String, String>{
    "Обзор": "Overview",
    "Продукты": "Products",
    "Инфра": "Infrastructure",
    "Ещё": "More",
    "Настройки": "Settings",
    "Меню компании": "Company menu",
    "Начать заново?": "Start over?",
    "Текущее локальное сохранение будет удалено.":
        "The current local save will be deleted.",
    "Сбросить": "Reset",
    "Отмена": "Cancel",
    "Стратегия": "Strategy",
    "Экосистема, капитал, внешний портфель, сделки и новости вынесены в отдельные разделы.":
        "Ecosystem, capital, external portfolio, deals, and news are organized into separate sections.",
    "Обучение и подсказки": "Tutorial and tips",
    "Коротко пройти основной цикл и механику продукта":
        "Review the core loop and product mechanics",
    "Метрики и терминология": "Metrics and terminology",
    "Центр проектов": "Project center",
    "Центр безопасности": "Security center",
    "Конкурентная разведка": "Competitive intelligence",
    "Клиентские контракты": "Client contracts",
    "Финансы и P&L": "Finance and P&L",
    "Экосистема продуктов": "Product ecosystem",
    "Инвесторы и cap table": "Investors and cap table",
    "Рынок и M&A": "Market and M&A",
    "Новости": "News",
    "Язык и валюта": "Language and currency",
    "Меняет отображение денег и ключевых новых экранов.":
        "Changes money display and the application language.",
    "Настройки симуляции": "Simulation settings",
    "Технические мини-игры": "Technical mini-games",
    "При отключении результат рассчитывается по навыкам команды.":
        "When disabled, outcomes are calculated from team skills.",
    "Инфраструктура": "Infrastructure",
    "Офисы": "Offices",
    "Серверные": "Server rooms",
    "Серверы": "Servers",
    "Мощности": "Capacity",
    "Текущая конфигурация": "Current configuration",
    "Офис": "Office",
    "Сотрудники": "Employees",
    "Серверная": "Server room",
    "Активный Compute": "Active compute",
    "Серверы в резерве": "Reserved servers",
    "Общая загрузка": "Total load",
    "Аренда офиса": "Office rental",
    "Вся команда remote: офис сейчас не списывает деньги.":
        "The whole team is remote: the office currently costs nothing.",
    "Комфорт влияет на мораль, вместимость — на предел команды.":
        "Comfort affects morale; capacity limits the on-site team.",
    "Арендовать": "Rent",
    "Бонус к найму": "Hiring bonus",
    "Престиж": "Prestige",
    "Депозит": "Deposit",
    "Аренда серверной": "Server room rental",
    "Серверное железо": "Server hardware",
    "Распределение compute": "Compute allocation",
    "Создайте продукт, чтобы распределять мощности.":
        "Create a product to allocate capacity.",
    "Продукт не найден": "Product not found",
    "Разработка продукта": "Product development",
    "Рабочий объём": "Work scope",
    "Осталось": "Remaining",
    "Штраф состава": "Staffing penalty",
    "Оптимальная команда": "Optimal team",
    "Языки покрыты": "Language coverage",
    "Роли покрыты": "Role coverage",
    "Эффективность состава": "Staffing efficiency",
    "Назначено сотрудников": "Assigned employees",
    "Управлять проектной командой": "Manage project team",
    "Выпустить продукт": "Launch product",
    "Специалисты для разработки": "Development specialists",
    "Свежесть продукта": "Product freshness",
    "Продукт против лидера рынка": "Product vs market leader",
    "Стек и функции": "Stack and features",
    "Технологический стек": "Technology stack",
    "Языки": "Languages",
    "Технологии": "Technologies",
    "Функции": "Features",
    "Собственная AI": "Internal AI",
    "Безопасность": "Security",
    "Мощность разработки": "Development capacity",
    "Пользователи": "Users",
    "Рейтинг": "Rating",
    "Загрузка": "Load",
    "Активация": "Activation",
    "Удержание 30 дн.": "Retention 30d",
    "Отток": "Churn",
    "Задержка": "Latency",
    "Коэффициент риска": "Incident multiplier",
    "Разовая настройка": "Setup",
    "Ориентир зарплат на разработку": "Estimated development payroll",
    "Мощность инфраструктуры": "Infrastructure capacity",
    "Нужные специалисты": "Required specialists",
    "Не выбраны": "None selected",
    "Управление безопасностью": "Security operations",
    "Безопасный SDLC": "Secure SDLC",
    "SAST + сканирование зависимостей": "SAST + dependency scanning",
    "WAF и защита от DDoS": "WAF and DDoS protection",
    "KMS и шифрование данных": "KMS and data encryption",
    "Фильтрация атак на периметре и защита публичных API от перегрузки.":
        "Perimeter attack filtering and protection of public APIs from overload.",
    "Мониторинг 24/7, централизованные логи и готовый сценарий локализации атаки.":
        "24/7 monitoring, centralized logs, and a ready incident containment playbook.",
    "Резервные копии и аварийное восстановление":
        "Backups and disaster recovery",
    "SOC и реагирование на инциденты": "SOC and incident response",
    "Безопасность приложений": "Application Security",
    "Моделирование угроз, обязательная проверка кода и чек-листы безопасности перед релизом.":
        "Threat modeling, mandatory code review, and security checklists before release.",
    "Автоматический поиск уязвимостей кода и зависимостей в каждой сборке.":
        "Automatic scanning for code and dependency vulnerabilities in every build.",
    "Раздельные ключи, ротация и шифрование данных при хранении для пользовательских данных.":
        "Separate keys, rotation, and encryption at rest for user data.",
    "Проверяемые резервные копии, отдельный контур восстановления и план восстановления.":
        "Verified backups, a separate recovery environment, and a recovery plan.",
    "Безопасная разработка, моделирование угроз и реакция на инциденты.":
        "Secure coding, threat modeling, and incident response.",
    "Льготный срок": "Grace period",
    "Расчётный риск": "Estimated risk",
    "Контролей внедрено": "Controls installed",
    "Покрытие ролей": "Role coverage",
    "Свежесть": "Freshness",
    "Последнее обновление": "Last update",
    "Рекламные кампании": "Advertising campaigns",
    "Рекламное агентство": "Advertising agency",
    "Канал закупки": "Acquisition channel",
    "Бюджет на 7 дней": "7-day budget",
    "Что будет закуплено": "What will be purchased",
    "Канал подходит продукту": "Channel fits the product",
    "Слабое попадание в аудиторию": "Weak audience fit",
    "Цена подписки": "Subscription price",
    "Вероятный эффект изменения": "Expected change impact",
    "Настройки монетизации": "Monetization settings",
    "Модель монетизации": "Monetization model",
    "Прогноз дохода / мес.": "Revenue forecast / month",
    "Инфраструктура и экосистема": "Infrastructure and ecosystem",
    "Выделено мощности": "Allocated capacity",
    "Доступно compute": "Available compute",
    "Требуется compute": "Required compute",
    "Загрузка выделения": "Allocation load",
    "Экосистемных связей": "Ecosystem links",
    "Экосистемный буст": "Ecosystem boost",
    "Команда": "Team",
    "Кандидаты": "Candidates",
    "Все роли": "All roles",
    "Сортировка": "Sort",
    "Зарплата": "Salary",
    "Надёжность": "Reliability",
    "Коммуникация": "Communication",
    "Только remote": "Remote only",
    "По фильтрам кандидаты не найдены.": "No candidates match the filters.",
    "Команда пуста. Наймите людей из рынка кандидатов.":
        "The team is empty. Hire people from the candidate market.",
    "Средние показатели": "Team averages",
    "Имя, роль или язык": "Name, role, or language",
    "Автоматический найм": "Auto-hire",
    "Нанять HR / People Partner": "Hire HR / People Partner",
    "HR / People Partner": "HR / People Partner",
    "Финансы компании": "Company finance",
    "Доход / мес.": "Income / month",
    "Расход / мес.": "Expense / month",
    "Прибыль / мес.": "Profit / month",
    "Прибыль / день": "Profit / day",
    "Ликвидность и кредит": "Liquidity and credit",
    "Активный кредит": "Active loan",
    "Нет": "None",
    "Подать заявку на бизнес-кредит": "Apply for a business loan",
    "Тестовые промокоды": "Test promo codes",
    "Промокод": "Promo code",
    "Применить": "Apply",
    "Динамика": "History",
    "Структура расходов": "Expense breakdown",
    "Зарплаты": "Salaries",
    "Офис и инфраструктура": "Office and infrastructure",
    "Продукты и маркетинг": "Products and marketing",
    "Корпоративная AI": "Corporate AI",
    "Инвесторы": "Investors",
    "Платежи по кредиту": "Loan payments",
    "Последние операции": "Recent transactions",
    "Разовых финансовых операций пока нет.":
        "No one-time financial transactions yet.",
    "Новая компания": "New company",
    "Название компании": "Company name",
    "Стартовый бюджет": "Starting budget",
    "Логотип": "Logo",
    "Кем CEO был раньше": "Founder background",
    "Навыки CEO": "Founder skills",
    "Создать компанию": "Create company",
    "Проектирование": "Planning",
    "Дизайн": "Design",
    "Отладка": "Debugging",
    "Что сейчас делает команда": "What the team is doing now",
    "Решить мини-задачу этапа": "Solve stage mini-challenge",
    "Задача на сегодня решена": "Today’s challenge completed",
    "Мини-задача": "Mini-challenge",
    "Правильно": "Correct",
    "Неверно": "Incorrect",
    "Начать новую компанию": "Start a new company",
    "Сайт компании": "Company website",
    "Cloud-платформа": "Cloud platform",
    "Командный SaaS": "Team SaaS",
    "Браузер": "Browser",
    "Криптокошелёк": "Crypto wallet",
    "Цифровая система города": "Digital city system",
  };

  static const Map<String, String> phrases = <String, String>{
    "не хватает денег": "insufficient funds",
    "не хватает": "not enough",
    "заблокирован": "blocked",
    "заблокирована": "blocked",
    "после релиза": "after release",
    "после выхода на рынок": "after launch",
    "новый продукт": "new product",
    "в разработке": "in development",
    "рабочих часов": "work hours",
    "рабочие часы": "work hours",
    "игровых дней": "game days",
    "игровой день": "game day",
    "в разделе": "in the section",
    "в команде": "on the team",
    "в проекте": "on the project",
    "к текущему продукту": "for the current product",
    "текущего продукта": "current product",
    "текущий продукт": "current product",
    "на рынке": "on the market",
    "выход на рынок": "market launch",
    "пользователей": "users",
    "пользователи": "users",
    "пользователь": "user",
    "настройка продукта": "product setup",
    "стартовая настройка": "initial setup",
    "технические улучшения": "technical improvements",
    "техническое улучшение": "technical improvement",
    "обновление продукта": "product update",
    "сначала завершите": "finish first",
    "не назначается": "is not assigned",
    "автоматический подбор": "automatic hiring",
    "точные метрики": "exact metrics",
    "пользовательские сегменты": "user segments",
    "активных контрактов": "active contracts",
    "активных кампаний": "active campaigns",
    "активных": "active",
    "выбранный продукт": "selected product",
    "выбранного продукта": "selected product",
    "текущая команда": "current team",
    "проектная команда": "project team",
    "критичны": "critical",
    "нужной роли": "required role",
    "нужные роли": "required roles",
    "текущие дефициты": "current deficits",
    "модель монетизации": "monetization model",
    "ежемесячные расходы": "monthly expenses",
    "месячный темп": "monthly run rate",
    "денежный поток": "cash flow",
    "отрицательный баланс": "negative balance",
    "текущий баланс": "current balance",
    "расходы идут через": "costs are paid through",
    "отдельной покупки нет": "there is no separate purchase",
    "компания оплачивает": "the company pays",
    "требует технологию": "requires technology",
    "требует": "requires",
    "не подходит": "does not fit",
    "максимум": "maximum",
    "минимум": "minimum",
    "выбрано": "selected",
    "доступна": "available",
    "доступен": "available",
    "недоступна": "unavailable",
    "недоступен": "unavailable",
    "сейчас": "now",
    "сначала": "first",
    "затем": "then",
    "примерно": "approximately",
    "снижается": "decreases",
    "увеличивается": "increases",
    "показывает": "shows",
    "показываются": "shown",
    "влияет": "affects",
    "влияют": "affect",
    "зависит": "depends",
    "зависят": "depend",
    "позволяет": "allows",
    "нельзя": "cannot",
    "можно": "can",
  };

  static const Map<String, String> words = <String, String>{
    "компания": "company",
    "компании": "company",
    "компанию": "company",
    "компанией": "company",
    "продукт": "product",
    "продукта": "product",
    "продукты": "products",
    "продуктов": "products",
    "продукту": "product",
    "команда": "team",
    "команды": "team",
    "команде": "team",
    "команду": "team",
    "сотрудник": "employee",
    "сотрудника": "employee",
    "сотрудники": "employees",
    "сотрудников": "employees",
    "кандидат": "candidate",
    "кандидаты": "candidates",
    "кандидатов": "candidates",
    "роль": "role",
    "роли": "role",
    "ролей": "roles",
    "день": "day",
    "дней": "days",
    "дня": "day",
    "дн": "days",
    "час": "hour",
    "часов": "hours",
    "ч": "h",
    "деньги": "cash",
    "денег": "cash",
    "цена": "price",
    "цену": "price",
    "цены": "prices",
    "расходы": "expenses",
    "расход": "expense",
    "доход": "income",
    "дохода": "income",
    "выручка": "revenue",
    "выручки": "revenue",
    "прибыль": "profit",
    "убыток": "loss",
    "аренда": "rent",
    "аренды": "rent",
    "офис": "office",
    "офиса": "office",
    "офисы": "offices",
    "сервер": "server",
    "серверы": "servers",
    "серверов": "servers",
    "серверная": "server room",
    "серверной": "server room",
    "мощность": "capacity",
    "мощности": "capacity",
    "нагрузка": "load",
    "нагрузки": "load",
    "проект": "project",
    "проекта": "project",
    "проектов": "projects",
    "проекте": "project",
    "разработка": "development",
    "разработки": "development",
    "разработку": "development",
    "проектирование": "planning",
    "проектирования": "planning",
    "дизайн": "design",
    "дизайна": "design",
    "отладка": "debugging",
    "отладки": "debugging",
    "улучшение": "improvement",
    "улучшения": "improvements",
    "улучшений": "improvements",
    "функция": "feature",
    "функции": "features",
    "функций": "features",
    "настройка": "setup",
    "настройки": "settings",
    "рынок": "market",
    "рынка": "market",
    "реклама": "advertising",
    "рекламы": "advertising",
    "маркетинг": "marketing",
    "маркетинга": "marketing",
    "безопасность": "security",
    "безопасности": "security",
    "надёжность": "reliability",
    "качество": "quality",
    "скорость": "speed",
    "прогресс": "progress",
    "рейтинг": "rating",
    "сохранение": "save",
    "сохранения": "saves",
    "загрузка": "loading",
    "ошибка": "error",
    "ошибки": "errors",
    "ошибок": "errors",
    "дефект": "bug",
    "дефекты": "bugs",
    "риск": "risk",
    "риски": "risks",
    "риска": "risk",
    "инвестор": "investor",
    "инвесторы": "investors",
    "инвесторов": "investors",
    "кредит": "loan",
    "кредита": "loan",
    "контракт": "contract",
    "контракты": "contracts",
    "контрактов": "contracts",
    "новости": "news",
    "новость": "news",
    "навык": "skill",
    "навыки": "skills",
    "навыков": "skills",
    "основатель": "founder",
    "основателя": "founder",
    "основателем": "founder",
    "переговоры": "negotiation",
    "рост": "growth",
    "доступно": "available",
    "недоступно": "unavailable",
    "активно": "active",
    "завершено": "completed",
    "создать": "create",
    "создание": "creation",
    "создан": "created",
    "создана": "created",
    "нанять": "hire",
    "найм": "hiring",
    "найма": "hiring",
    "нанят": "hired",
    "наняла": "hired",
    "нанял": "hired",
    "купить": "buy",
    "покупка": "purchase",
    "арендовать": "rent",
    "выбрать": "select",
    "выберите": "select",
    "выбран": "selected",
    "выбранный": "selected",
    "запустить": "launch",
    "запуск": "launch",
    "выпустить": "launch",
    "релиз": "release",
    "релиза": "release",
    "удалённо": "remote",
    "удалённый": "remote",
    "удалённая": "remote",
    "нужно": "required",
    "нужен": "required",
    "нужна": "required",
    "нужны": "required",
    "текущий": "current",
    "текущая": "current",
    "текущее": "current",
    "текущие": "current",
    "новый": "new",
    "новая": "new",
    "новое": "new",
    "новые": "new",
    "первый": "first",
    "первая": "first",
    "первые": "first",
    "последний": "last",
    "последнее": "last",
    "последние": "recent",
    "общий": "total",
    "общая": "total",
    "общие": "total",
    "свободно": "free",
    "занято": "occupied",
    "мест": "seats",
    "места": "seats",
    "комфорт": "comfort",
    "престиж": "prestige",
    "депозит": "deposit",
    "питание": "power",
    "охлаждение": "cooling",
    "уровень": "level",
    "уровня": "level",
    "причина": "reason",
    "причины": "reasons",
    "решение": "solution",
    "решения": "solutions",
    "сильный": "strong",
    "слабый": "weak",
    "слабое": "weak",
    "высокий": "high",
    "низкий": "low",
    "низкая": "low",
    "высокая": "high",
    "готовность": "readiness",
    "готов": "ready",
    "готова": "ready",
    "только": "only",
    "всегда": "always",
    "никогда": "never",
    "без": "without",
    "для": "for",
    "после": "after",
    "до": "before",
    "через": "in",
    "пример": "example",
    "сейчас": "now",
    "уже": "already",
    "ещё": "more",
    "нет": "none",
    "да": "yes",
    "отмена": "cancel",
    "сохранить": "save",
    "закрыть": "close",
    "назад": "back",
    "далее": "next",
  };
}
